# Generated by Django 4.1.3 on 2023-01-11 14:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("base", "0004_question_participants_alter_point_points_message"),
    ]

    operations = [
        migrations.AlterField(
            model_name="message",
            name="dislike",
            field=models.ManyToManyField(
                blank=True,
                default=0,
                related_name="dislike_message",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="message",
            name="like",
            field=models.ManyToManyField(
                blank=True,
                default=0,
                related_name="like_message",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
