# Generated by Django 4.1.3 on 2023-01-12 10:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("base", "0005_alter_message_dislike_alter_message_like"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="dislike",
            field=models.ManyToManyField(
                blank=True, related_name="dislike_post", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="question",
            name="like",
            field=models.ManyToManyField(
                blank=True, related_name="like_post", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="message",
            name="dislike",
            field=models.ManyToManyField(
                blank=True, related_name="dislike_message", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="message",
            name="like",
            field=models.ManyToManyField(
                blank=True, related_name="like_message", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
