# Generated by Django 4.1.3 on 2023-01-12 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0006_question_dislike_question_like_alter_message_dislike_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="correct",
            field=models.BooleanField(default=False),
        ),
    ]
