# Generated by Django 4.1.3 on 2023-01-27 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0010_alter_profile_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="cover_img",
            field=models.ImageField(
                blank=True,
                default="imgs/cover_img/default.jpg",
                null=True,
                upload_to="imgs/cover_img",
            ),
        ),
    ]
