# Generated by Django 4.1.3 on 2023-01-27 15:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("base", "0011_profile_cover_img"),
    ]

    operations = [
        migrations.AlterField(
            model_name="point",
            name="user",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="topextendprofile",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
