# Generated by Django 4.1.3 on 2023-01-28 12:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("base", "0014_profile_following"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="follower",
            field=models.ManyToManyField(
                blank=True, related_name="follower", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="following",
            field=models.ManyToManyField(
                blank=True, related_name="following", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
